/**
 * This file defines the RootLayout component for a Next.js application.
 * It includes metadata definitions and the use of a Google font (Inter) for styling.
 * The RootLayout component wraps other components and is used at the top level of the application to provide a consistent layout structure.

* Project Name: Beautiful Gate Cafe Website
 * File Purpose: Description of the specific file's purpose (e.g., Home Component, Global Styles)
 * Author: Jonathan Legro
 * Created Date: YYYY-MM-DD
 * Last Modified: YYYY-MM-DD
 * Notes: Any additional notes or references about the file
 */


// Importing types for TypeScript support
import type { Metadata } from "next";
// Importing the Inter font from Google's font library through the next/font module
import { Inter } from "next/font/google";
// Importing global CSS styles
import "./globals.css";

// Initializing the Inter font with specific subsets
const inter = Inter({ subsets: ["latin"] });

// Defining metadata for the application using the imported Metadata type
export const metadata: Metadata = {
  title: "Create Next App", // Title of the application
  description: "Generated by create next app", // Description of the application
};

// Exporting the default RootLayout functional component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Specifying that children must be React nodes
}>) {
  return (
    // Setting the language of the document to English
    <html lang="en">
      {/* Applying the Inter font class to the body and wrapping children components */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
